import { Manrope } from 'next/font/google'
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import '../Assets/Scss/Styles.scss'
import "../Assets/Scss/font.scss";
import "../Assets/Scss/fontSize.scss";



const manrope = Manrope({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
})

// app/layout.js or app/layout.tsx
export const metadata = {
  title: "ELint",
  description: "generated by elint website",
  icons: {
    icon: [
      {
        url: '/Elint.png',
        sizes: 'any',
      },
      {
         url: '/Elint.png',
        type: 'image/png',
        sizes: '48x48',
      },
    ],
    apple: [
      {
         url: '/Elint.png',
        sizes: '180x180',
        type: 'image/png',
      },
    ],
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navbar/>
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
